@CategorizationAgent_HostAddress = http://localhost:5273

### Inquiry Classification With Action Workflow 실행 (HTTP)
GET {{CategorizationAgent_HostAddress}}/run-classification-with-action
Accept: application/json
